name: Build → Push to ECR → Deploy Lambda

on:
  push:
    branches:
      - main
    # 可按需改成特定路径触发，例如只在 Dockerfile / src 改动时触发
    paths:
      - 'Dockerfile'
      - '*.py'

env:
  AWS_REGION: ap-southeast-2               # 改为你的 region
  ECR_REPOSITORY: wordlecracker            # ECR 仓库名（不含 account/region）
  LAMBDA_FUNCTION_NAME: wordlecracker-container  # 要更新的 Lambda 名
  IMAGE_TAG: ${{ github.sha }}             # 用 commit sha 作为 tag（可改成 v1, latest 等）
  # ECR registry 会以 accountId.dkr.ecr.<region>.amazonaws.com 形式拼出
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

permissions:
  contents: read
  id-token: write        # 如果想用 OIDC，可改成用 OIDC flow（需要额外配置）
  # AWS credentials via secrets below will be used by configure-aws-credentials

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU (buildx) for cross-platform builds
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push image to ECR (single-platform linux/amd64)
      id: build-and-push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
        platforms: linux/amd64
        provenance: false   # 关闭 provenance 防止生成 OCI attestation/index
        sbom: false         # 关闭 SBOM 输出，避免生成额外 index entries

    - name: Wait a few seconds for ECR consistency
      run: sleep 5

    - name: Get latest pushed image digest from ECR
      id: get-digest
      run: |
        # Query ECR for the most recently pushed image in this repository.
        # We use sort_by(imageDetails,& imagePushedAt)[-1] to pick the newest image.
        REPO="${{ env.ECR_REPOSITORY }}"
        ACCOUNT="${{ secrets.AWS_ACCOUNT_ID }}"
        REGION="${{ env.AWS_REGION }}"
        # get image digest (sha256:...)
        DIGEST=$(aws ecr describe-images --repository-name "$REPO" --region "$REGION" --query 'imageDetails[1].imageDigest' --output text)
        if [ -z "$DIGEST" ] || [ "$DIGEST" = "None" ]; then
          echo "Failed to get image digest from ECR"
          exit 1
        fi
        echo "Found digest: $DIGEST"
        # expose for following steps
        echo "image_digest=$DIGEST" >> $GITHUB_OUTPUT
        echo "image_uri=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}@$DIGEST" >> $GITHUB_OUTPUT

    - name: Update Lambda function code to use new image (by digest)
      id: update-lambda
      run: |
        IMAGE_URI="${{ steps.get-digest.outputs.image_uri }}"
        echo "Updating Lambda ${{ env.LAMBDA_FUNCTION_NAME }} to image $IMAGE_URI"
        aws lambda update-function-code --function-name "${{ env.LAMBDA_FUNCTION_NAME }}" --image-uri "$IMAGE_URI" --region "${{ env.AWS_REGION }}"
      env:
        AWS_REGION: ${{ env.AWS_REGION }}

    - name: Show Lambda update result
      run: |
        echo "Lambda update completed. Describe function to verify:"
        aws lambda get-function --function-name "${{ env.LAMBDA_FUNCTION_NAME }}" --region "${{ env.AWS_REGION }}"
